version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  nodeapp:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - webdata:/var/lib/web
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_NAME=url-shortner
      - DB_USER=shortner
      - DB_PASSWORD=shortnerpwd

volumes:
  mysql_data:
  webdata: