services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'roots'
      MYSQL_DATABASE: 'short'
      MYSQL_USER: 'short'
      MYSQL_PASSWORD: 'short'
      SERVICE_NAME: 'mysqldb'
    ports:
      - 3307:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-db-network
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: mrarunsingh8/url-shortner-express:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      SERVER_PORT: 3000
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_NAME: 'short'
      DB_USER: 'short'
      DB_PASSWORD: 'short'
    stdin_open: true
    tty: true
    depends_on:
      - mysqldb
    networks:
      - app-db-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app


volumes:
  db-data:

networks:
  app-db-network:
    driver: bridge